schema-version: v1
kind: plugin
metadata:
  name: plugin-input-global-tests
  display-name: plugin-input-global-tests
  description: Template used to test global inputs
  version: 0.0.2
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.2.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  inputs:
    - label: Global input 1
      type: text
      name: global_input_1
      global: true
      default: 'Global-Value-Of-Input-1'
    - label: Global input 2
      type: text
      name: global_input_2
      global: true
      default: 'Global-Value-Of-Input-2'
    - label: Global input 3
      type: text
      name: global_input_3
      global: true
      default: 'Global-Value-Of-Input-3'            
  computed-inputs:
    computed_input_1: "{{ global_input_1 | upper }}"
    computed_input_2: "{{ global_input_2 | upper }}"
    computed_input_3: "{{ global_input_3 | upper }}"
  global-computed-inputs:
    global_computed_input_1: "{{ global_input_1 | lower}}"
    global_computed_input_2: "{{ global_input_2 | lower}}"
    global_computed_input_3: "{{ global_input_3 | lower}}"

