schema-version: v1
kind: plugin
metadata:
  name: plugin-input-help-tests
  display-name: plugin-input-help-tests
  description: Template used to test help field of the inputs
  version: 0.0.3
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.3.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  inputs:
    - label: Text field
      type: text
      name: text_field
      default: test
      help: "Text field help"
    - label: Boolean field
      type: bool
      name: boolean_field
      default: true
      help: "Boolean field help"
    - label: Integer field
      type: int
      name: integer_field
      default: 1
      help: "Integer field help"
    - label: Password field
      type: password
      name: password_field
      default: 123
      help: "Password field help"
    - label: Select field
      type: text
      name: select_field
      items:
        - "python"
        - "java"
        - "golang"
        - "javascript"
      default: "python"
      help: "Select field help"
    - label: Multiselect field
      type: multiselect
      name: multiselect_field
      items:
        - item1
        - item2
        - item3
        - item4
      default: [item4]
      help: "Multiselect field help"
