schema-version: v1
kind: plugin
metadata:
  name: plugin-input-tests
  display-name: plugin-input-tests
  description: Template used to test inputs
  version: 0.0.3
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.3.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  inputs:
    - label: Text field
      type: text
      name: text_field
      default: test
    - label: Boolean field
      type: bool
      name: boolean_field
      default: true
    - label: Boolean field 2 
      type: bool
      name: boolean_field2  
    - label: Integer field
      type: int
      name: integer_field
      default: 1
    - label: Integer field 2
      type: int
      name: integer_field2 
    - label: Password field
      type: password
      name: password_field
      default: 123
    - label: Select field # O input select é um input text com items.
      type: text
      name: select_field
      items:
          - "python"
          - "java"
          - "golang"
          - "javascript"
      default: "python"   
    - label: Select field 2
      type: text
      name: select_field2
      items:
          - "python"
          - "java"
          - "golang"
          - "javascript"
    - label: Multiselect field
      type: multiselect
      name: multiselect_field
      items:
        - item1
        - item2
        - item3
        - item4
      default: [item4]
    - label: Multiselect field 2
      type: multiselect
      name: multiselect_field2
      items:
        - item1
        - item2
        - item3
        - item4  
